version: '2.4'
networks:
  iot_net:
    driver: bridge
volumes:
  api_vol:
  model_vol:
  data_vol:
  db_vol:

services:
  api:
    build:
      context: ./api
      dockerfile: DockerFile
    volumes:
    - api_vol:/usr/src/app
    ports:
      - 80:5000
    environment:
    - FLASK_DEBUG=1
    - APP_SETTINGS=src.config.DevelopmentConfig
    - FLASK_ENV=development
    container_name: api
    networks:
      - iot_net
    depends_on:
      - iot_database
      - model

  model:
    ports:
      - 81:5000
    expose:
      - '5000'
    build:
      context: ./model
      dockerfile: DockerFile
    volumes:
      - model_vol:/usr/src/app
      - data_vol:/usr/src/app/data
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=src.config.DevelopmentConfig
      - FLASK_ENV=development
    depends_on:
      - iot_database
    container_name: model
    networks:
      - iot_net

  iot_database:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    build:
      context: ./database
      dockerfile: DockerFile
    volumes:
      - db_vol:/var/lib/postgresql/data
    container_name: iot_db
    networks:
      - iot_net
